# Changes here will be overwritten by Copier
_commit: v1
_src_path: git+https://github.com/WaylonWalker/markata-blog-starter
author_email: test
author_fullname: test
author_twitter: '@test'
description: A blog created from the markata blog-starter
project_name: markata-starter-blog-example
python_package_import_name: markata_starter_blog_example
url: https://example.com

